import {MigrationInterface, QueryRunner} from "typeorm";

export class migration1614176800206 implements MigrationInterface {
    name = 'migration1614176800206'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "task" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "inputs" text, "hardTimeout" integer NOT NULL DEFAULT (86400000), "name" varchar NOT NULL, "process" varchar NOT NULL, "softTimeout" integer NOT NULL DEFAULT (86400000), CONSTRAINT "UQ_20f1f21d6853d9d20d501636ebd" UNIQUE ("name"))`);
        await queryRunner.query(`CREATE TABLE "schedule_task" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "abortEarly" boolean NOT NULL DEFAULT (1), "delayAfter" integer NOT NULL DEFAULT (0), "onError" text, "step" integer NOT NULL, "scheduleId" integer NOT NULL, "taskId" integer NOT NULL, CONSTRAINT "step_scheduleId" UNIQUE ("step", "scheduleId"))`);
        await queryRunner.query(`CREATE TABLE "schedule" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "force" boolean NOT NULL DEFAULT (0), "name" varchar NOT NULL, "hardForceTime" integer NOT NULL DEFAULT (1800000), "hardTimeout" integer NOT NULL DEFAULT (86400000), "onError" text, "priority" integer NOT NULL DEFAULT (50), "rule" varchar NOT NULL, "softForceTime" integer NOT NULL DEFAULT (900000), "softTimeout" integer NOT NULL DEFAULT (86400000), "validFrom" datetime NOT NULL, "validUntil" datetime NOT NULL DEFAULT ('9999-12-31T00:00:00.000Z'), "waitTime" integer NOT NULL DEFAULT (86400000), "runtimeResourceId" integer NOT NULL, CONSTRAINT "UQ_15663a2014348b782e7058542e1" UNIQUE ("name"))`);
        await queryRunner.query(`CREATE TABLE "runtime_resource" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "apiKey" varchar, "auth" varchar NOT NULL, "friendlyName" varchar NOT NULL, "hostname" varchar NOT NULL, "https" boolean NOT NULL DEFAULT (1), "password" varchar, "port" integer NOT NULL, "username" varchar)`);
        await queryRunner.query(`CREATE TABLE "job" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "addTime" datetime NOT NULL, "endTime" datetime, "message" varchar, "priority" integer NOT NULL DEFAULT (50), "sessionId" varchar, "startTime" datetime, "startReason" varchar NOT NULL, "status" varchar NOT NULL, "step" integer NOT NULL DEFAULT (1), "steps" text, "stopReason" varchar, "subStep" integer NOT NULL DEFAULT (1), "updateTime" datetime NOT NULL DEFAULT (datetime('now')), "runtimeResourceId" integer NOT NULL, "scheduleId" integer NOT NULL)`);
        await queryRunner.query(`CREATE TABLE "job_log" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "addTime" datetime NOT NULL, "endTime" datetime, "message" varchar, "priority" integer NOT NULL DEFAULT (50), "sessionId" varchar, "startTime" datetime, "startReason" varchar NOT NULL, "status" varchar NOT NULL, "step" integer NOT NULL DEFAULT (1), "steps" text, "stopReason" varchar, "subStep" integer NOT NULL DEFAULT (1), "updateTime" datetime NOT NULL DEFAULT (datetime('now')), "jobId" integer NOT NULL, "scheduleId" integer NOT NULL, "runtimeResourceId" integer NOT NULL)`);
        await queryRunner.query(`CREATE TABLE "user" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "apiKey" varchar, "admin" boolean NOT NULL DEFAULT (0), "name" varchar NOT NULL, "password" varchar, CONSTRAINT "UQ_065d4d8f3b5adb4a08841eae3c8" UNIQUE ("name"))`);
        await queryRunner.query(`CREATE TABLE "temporary_schedule_task" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "abortEarly" boolean NOT NULL DEFAULT (1), "delayAfter" integer NOT NULL DEFAULT (0), "onError" text, "step" integer NOT NULL, "scheduleId" integer NOT NULL, "taskId" integer NOT NULL, CONSTRAINT "step_scheduleId" UNIQUE ("step", "scheduleId"), CONSTRAINT "FK_d95bd16410db6dc3e20321934b3" FOREIGN KEY ("scheduleId") REFERENCES "schedule" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_e10cfa597abaf6bb86ed247aca2" FOREIGN KEY ("taskId") REFERENCES "task" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_schedule_task"("id", "abortEarly", "delayAfter", "onError", "step", "scheduleId", "taskId") SELECT "id", "abortEarly", "delayAfter", "onError", "step", "scheduleId", "taskId" FROM "schedule_task"`);
        await queryRunner.query(`DROP TABLE "schedule_task"`);
        await queryRunner.query(`ALTER TABLE "temporary_schedule_task" RENAME TO "schedule_task"`);
        await queryRunner.query(`CREATE TABLE "temporary_schedule" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "force" boolean NOT NULL DEFAULT (0), "name" varchar NOT NULL, "hardForceTime" integer NOT NULL DEFAULT (1800000), "hardTimeout" integer NOT NULL DEFAULT (86400000), "onError" text, "priority" integer NOT NULL DEFAULT (50), "rule" varchar NOT NULL, "softForceTime" integer NOT NULL DEFAULT (900000), "softTimeout" integer NOT NULL DEFAULT (86400000), "validFrom" datetime NOT NULL, "validUntil" datetime NOT NULL DEFAULT ('9999-12-31T00:00:00.000Z'), "waitTime" integer NOT NULL DEFAULT (86400000), "runtimeResourceId" integer NOT NULL, CONSTRAINT "UQ_15663a2014348b782e7058542e1" UNIQUE ("name"), CONSTRAINT "FK_22e60336c6248f94e94767f7d91" FOREIGN KEY ("runtimeResourceId") REFERENCES "runtime_resource" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_schedule"("id", "force", "name", "hardForceTime", "hardTimeout", "onError", "priority", "rule", "softForceTime", "softTimeout", "validFrom", "validUntil", "waitTime", "runtimeResourceId") SELECT "id", "force", "name", "hardForceTime", "hardTimeout", "onError", "priority", "rule", "softForceTime", "softTimeout", "validFrom", "validUntil", "waitTime", "runtimeResourceId" FROM "schedule"`);
        await queryRunner.query(`DROP TABLE "schedule"`);
        await queryRunner.query(`ALTER TABLE "temporary_schedule" RENAME TO "schedule"`);
        await queryRunner.query(`CREATE TABLE "temporary_job" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "addTime" datetime NOT NULL, "endTime" datetime, "message" varchar, "priority" integer NOT NULL DEFAULT (50), "sessionId" varchar, "startTime" datetime, "startReason" varchar NOT NULL, "status" varchar NOT NULL, "step" integer NOT NULL DEFAULT (1), "steps" text, "stopReason" varchar, "subStep" integer NOT NULL DEFAULT (1), "updateTime" datetime NOT NULL DEFAULT (datetime('now')), "runtimeResourceId" integer NOT NULL, "scheduleId" integer NOT NULL, CONSTRAINT "FK_8008dc901f6093ac0861d498b0e" FOREIGN KEY ("runtimeResourceId") REFERENCES "runtime_resource" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_de9f5297606ba659814388cdb0c" FOREIGN KEY ("scheduleId") REFERENCES "schedule" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_job"("id", "addTime", "endTime", "message", "priority", "sessionId", "startTime", "startReason", "status", "step", "steps", "stopReason", "subStep", "updateTime", "runtimeResourceId", "scheduleId") SELECT "id", "addTime", "endTime", "message", "priority", "sessionId", "startTime", "startReason", "status", "step", "steps", "stopReason", "subStep", "updateTime", "runtimeResourceId", "scheduleId" FROM "job"`);
        await queryRunner.query(`DROP TABLE "job"`);
        await queryRunner.query(`ALTER TABLE "temporary_job" RENAME TO "job"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "job" RENAME TO "temporary_job"`);
        await queryRunner.query(`CREATE TABLE "job" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "addTime" datetime NOT NULL, "endTime" datetime, "message" varchar, "priority" integer NOT NULL DEFAULT (50), "sessionId" varchar, "startTime" datetime, "startReason" varchar NOT NULL, "status" varchar NOT NULL, "step" integer NOT NULL DEFAULT (1), "steps" text, "stopReason" varchar, "subStep" integer NOT NULL DEFAULT (1), "updateTime" datetime NOT NULL DEFAULT (datetime('now')), "runtimeResourceId" integer NOT NULL, "scheduleId" integer NOT NULL)`);
        await queryRunner.query(`INSERT INTO "job"("id", "addTime", "endTime", "message", "priority", "sessionId", "startTime", "startReason", "status", "step", "steps", "stopReason", "subStep", "updateTime", "runtimeResourceId", "scheduleId") SELECT "id", "addTime", "endTime", "message", "priority", "sessionId", "startTime", "startReason", "status", "step", "steps", "stopReason", "subStep", "updateTime", "runtimeResourceId", "scheduleId" FROM "temporary_job"`);
        await queryRunner.query(`DROP TABLE "temporary_job"`);
        await queryRunner.query(`ALTER TABLE "schedule" RENAME TO "temporary_schedule"`);
        await queryRunner.query(`CREATE TABLE "schedule" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "force" boolean NOT NULL DEFAULT (0), "name" varchar NOT NULL, "hardForceTime" integer NOT NULL DEFAULT (1800000), "hardTimeout" integer NOT NULL DEFAULT (86400000), "onError" text, "priority" integer NOT NULL DEFAULT (50), "rule" varchar NOT NULL, "softForceTime" integer NOT NULL DEFAULT (900000), "softTimeout" integer NOT NULL DEFAULT (86400000), "validFrom" datetime NOT NULL, "validUntil" datetime NOT NULL DEFAULT ('9999-12-31T00:00:00.000Z'), "waitTime" integer NOT NULL DEFAULT (86400000), "runtimeResourceId" integer NOT NULL, CONSTRAINT "UQ_15663a2014348b782e7058542e1" UNIQUE ("name"))`);
        await queryRunner.query(`INSERT INTO "schedule"("id", "force", "name", "hardForceTime", "hardTimeout", "onError", "priority", "rule", "softForceTime", "softTimeout", "validFrom", "validUntil", "waitTime", "runtimeResourceId") SELECT "id", "force", "name", "hardForceTime", "hardTimeout", "onError", "priority", "rule", "softForceTime", "softTimeout", "validFrom", "validUntil", "waitTime", "runtimeResourceId" FROM "temporary_schedule"`);
        await queryRunner.query(`DROP TABLE "temporary_schedule"`);
        await queryRunner.query(`ALTER TABLE "schedule_task" RENAME TO "temporary_schedule_task"`);
        await queryRunner.query(`CREATE TABLE "schedule_task" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "abortEarly" boolean NOT NULL DEFAULT (1), "delayAfter" integer NOT NULL DEFAULT (0), "onError" text, "step" integer NOT NULL, "scheduleId" integer NOT NULL, "taskId" integer NOT NULL, CONSTRAINT "step_scheduleId" UNIQUE ("step", "scheduleId"))`);
        await queryRunner.query(`INSERT INTO "schedule_task"("id", "abortEarly", "delayAfter", "onError", "step", "scheduleId", "taskId") SELECT "id", "abortEarly", "delayAfter", "onError", "step", "scheduleId", "taskId" FROM "temporary_schedule_task"`);
        await queryRunner.query(`DROP TABLE "temporary_schedule_task"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TABLE "job_log"`);
        await queryRunner.query(`DROP TABLE "job"`);
        await queryRunner.query(`DROP TABLE "runtime_resource"`);
        await queryRunner.query(`DROP TABLE "schedule"`);
        await queryRunner.query(`DROP TABLE "schedule_task"`);
        await queryRunner.query(`DROP TABLE "task"`);
    }

}
